-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    id serial NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(20) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    shares integer NOT NULL,
    password VARCHAR(64) NOT NULL,
    role VARCHAR(5) NOT NULL DEFAULT 'voter',
    is_present boolean NOT NULL DEFAULT True,
    PRIMARY KEY (id),
    CHECK (role IN ('admin', 'voter'))
);

CREATE TABLE IF NOT EXISTS public."Vote"
(
    id serial NOT NULL,
    answer_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (answer_id, user_id)
);

CREATE TABLE IF NOT EXISTS public."Survey"
(
    id serial NOT NULL,
    title VARCHAR(50) NOT NULL,
    statement VARCHAR(200) NOT NULL,
    user_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT True,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Answer"
(
    id serial NOT NULL,
    survey_id integer NOT NULL,
    option VARCHAR(70) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Vote"
    ADD FOREIGN KEY (answer_id)
    REFERENCES public."Answer" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Vote"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Survey"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Answer"
    ADD FOREIGN KEY (survey_id)
    REFERENCES public."Survey" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

ALTER TABLE IF EXISTS public."User"
    ADD CONSTRAINT numeric_code
    CHECK (code ~ '^\d+$');

ALTER TABLE IF EXISTS public."User"
    ADD CONSTRAINT unique_code
    UNIQUE (code);

ALTER TABLE IF EXISTS public."User"
    ADD CONSTRAINT check_shares_positive CHECK (shares >= 0);

END;





-- Privileges
BEGIN;

-- Add privileges on all tables in the public schema
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO votes_admin_db;

-- Add privileges on all sequences in the public schema
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO votes_admin_db;

INSERT INTO public."User" (code, name, last_name,shares, password, role, is_present) VALUES ('12345678', 'admin', 'admin', 0, '$2b$10$Sx7ZOLL21yC0nQkxrCL86ugamY1OZOB5TL556nkGd8GcJPfMLjiZ.', 'admin', True);

COMMIT;
