FROM node:18

WORKDIR /app

# copy backend package definitions
COPY backend-src/package*.json ./

RUN npm install

# copy backend source code
COPY backend-src/ ./

# include frontend static files (build context is root)
COPY frontend-dist/share/nginx/html ./public

RUN npm run build

CMD [ "npm", "run", "start:prod" ]